---
kind: pipeline
type: docker
name: default

steps:
- name: install, build doc run scripts
  image: python:3.8
  commands:
  - git fetch --tags 
  - pip install sphinx sphinx_rtd_theme wheel Cython
  - python setup.py install
  - cd doc
  - make html
  - cd ../scripts
  - python circuit4_3D.py
  - python thermal/unidimensional_medium.py 

- name: develop
  image: python:3.8
  commands:
  - pip install Cython
  - python setup.py develop

- name: sdist, bdist, wheel
  image: python:3.8
  commands:
  - pip install Cython wheel
  - python setup.py bdist_wheel

- name: upload_doc_master
  image: appleboy/drone-scp
  when: 
    branch: 
      - master
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/hydraulic/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password
